export const RECEIVE_MESSAGE_LIST = 'RECEIVE_MESSAGE_LIST';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const REVERSE_MESSAGE = 'REVERSE_MESSAGE';
